@echo off
mkdir "Table Audio"
mkdir Wheels
mkdir "Wheels 2"
mkdir "Backglass Images"

copy /Y "Tables\Arcade\Res\tracks\game_theme0.ogg" "Table Audio\arcade.ogg"
copy /Y "Tables\DaVinci\Res\tracks\game_music.ogg" "Table Audio\davinci.ogg"
copy /Y "Tables\DragRacing\Res\tracks\drag_racing_gameplay1.ogg" "Table Audio\streetracing.ogg"
copy /Y "Tables\Fantasy\Res\tracks\fantasy_gameplay1.ogg" "Table Audio\fantasy.ogg"
copy /Y "Tables\Fourth\Res\tracks\gameplay1.ogg" "Table Audio\dreamland.ogg"
copy /Y "Tables\Halloween\Res\tracks\HW_gameplay_1.ogg" "Table Audio\halloween.ogg"
copy /Y "Tables\JungleStyle\Res\tracks\drums_igra.ogg" "Table Audio\jungle.ogg"
copy /Y "Tables\Mafia\Res\tracks\gameplay1.ogg" "Table Audio\mafia.ogg"
copy /Y "Tables\Pirates\Res\tracks\Pirates_Pinball_gameplay1.ogg" "Table Audio\pirates.ogg"
copy /Y "Tables\RedPlanet\Res\tracks\RP_gameplay_1.ogg" "Table Audio\redplanet.ogg"
copy /Y "Tables\Snow\Res\tracks\game_music.ogg" "Table Audio\snow.ogg"
copy /Y "Tables\Tanks\Res\tracks\game_music.ogg" "Table Audio\tanks.ogg"
copy /Y "Tables\TheDeep\Res\tracks\game_music.ogg" "Table Audio\deep.ogg"
copy /Y "Tables\Vikings\Res\tracks\gameplay1.ogg" "Table Audio\vikings.ogg"
copy /Y "Tables\WildWest\Res\tracks\game_music.ogg" "Table Audio\wildwest.ogg"
copy /Y "Tables\Zombie\Res\tracks\zombie_gameplay1.ogg" "Table Audio\zombie.ogg"

copy /Y "Res\textures\ap_splash.png" "Backglass Images\arcade.png"
copy /Y "Res\textures\dr_splash.png" "Backglass Images\streetracing.png"
copy /Y "Res\textures\dv_splash.png" "Backglass Images\davinci.png"
copy /Y "Res\textures\fo_splash.png" "Backglass Images\dreamland.png"
copy /Y "Res\textures\fy_splash.png" "Backglass Images\fantasy.png"
copy /Y "Res\textures\hw_splash.png" "Backglass Images\halloween.png"
copy /Y "Res\textures\js_splash.png" "Backglass Images\jungle.png"
copy /Y "Res\textures\pt_splash.png" "Backglass Images\pirates.png"
copy /Y "Res\textures\rp_splash.png" "Backglass Images\redplanet.png"
copy /Y "Res\textures\td_splash.png" "Backglass Images\deep.png"
copy /Y "Res\textures\tk_splash.png" "Backglass Images\tanks.png"
copy /Y "Res\textures\vk_splash.png" "Backglass Images\vikings.png"
copy /Y "Res\textures\ww_splash.png" "Backglass Images\wildwest.png"
copy /Y "Res\textures\zo_splash.png" "Backglass Images\zombie.png"
copy /Y "Res\textures\mf_splash.png" "Backglass Images\mafia.png"
copy /Y "Res\textures\sn_splash.png" "Backglass Images\snow.png"

copy /Y "Res\images\ap_icon.png" "Wheels 2\arcade.png"
copy /Y "Res\images\dr_icon.png" "Wheels 2\streetracing.png"
copy /Y "Res\images\dv_icon.png" "Wheels 2\davinci.png"
copy /Y "Res\images\fo_icon.png" "Wheels 2\dreamland.png"
copy /Y "Res\images\fy_icon.png" "Wheels 2\fantasy.png"
copy /Y "Res\images\hw_icon.png" "Wheels 2\halloween.png"
copy /Y "Res\images\js_icon.png" "Wheels 2\jungle.png"
copy /Y "Res\images\pt_icon.png" "Wheels 2\pirates.png"
copy /Y "Res\images\rp_icon.png" "Wheels 2\redplanet.png"
copy /Y "Res\images\td_icon.png" "Wheels 2\deep.png"
copy /Y "Res\images\tk_icon.png" "Wheels 2\tanks.png"
copy /Y "Res\images\vk_icon.png" "Wheels 2\vikings.png"
copy /Y "Res\images\ww_icon.png" "Wheels 2\wildwest.png"
copy /Y "Res\images\zo_icon.png" "Wheels 2\zombie.png"
copy /Y "Res\images\mf_icon.png" "Wheels 2\mafia.png"
copy /Y "Res\images\sn_icon.png" "Wheels 2\snow.png"

copy /Y "Res\images\ArcadeCover.png" "Wheels\arcade.png"
copy /Y "Res\images\DragRacingCover.png" "Wheels\streetracing.png"
copy /Y "Res\images\DaVinciCover.png" "Wheels\davinci.png"
copy /Y "Res\images\FourthCover.png" "Wheels\dreamland.png"
copy /Y "Res\images\FantasyCover.png" "Wheels\fantasy.png"
copy /Y "Res\images\HalloweenCover.png" "Wheels\halloween.png"
copy /Y "Res\images\JungleStyleCover.png" "Wheels\jungle.png"
copy /Y "Res\images\PiratesCover.png" "Wheels\pirates.png"
copy /Y "Res\images\RedPlanetCover.png" "Wheels\redplanet.png"
copy /Y "Res\images\TheDeepCover.png" "Wheels\deep.png"
copy /Y "Res\images\TanksCover.png" "Wheels\tanks.png"
copy /Y "Res\images\VikingsCover.png" "Wheels\vikings.png"
copy /Y "Res\images\WildWestCover.png" "Wheels\wildwest.png"
copy /Y "Res\images\ZombieCover.png" "Wheels\zombie.png"
copy /Y "Res\images\MafiaCover.png" "Wheels\mafia.png"
copy /Y "Res\images\SnowCover.png" "Wheels\snow.png"